### PR TITLE
added and styled tooltip

### LINKED ISSUE #383: Display submission.status_detail
Currently, we store submission status details when supplied (typically just in fail states) 
These are not displayed anywhere so participants are not informed of why their submission failed, just that it did. 
This detail should be easily accessible... somewhere. Could be tooltip present on failed submission in the submission manager table. Or somewhere else that makes better UI/UX sense? 
Open to ideas.

### PR DESCRIPTION
**Pull request by Germs31**
# @ mention of reviewers
@jimmykodes @ckcollab 

# A brief description of the purpose of the changes contained in this PR.
added 
Added a toop tip that shows status details on hover. 

# Issues this PR resolves
resolves #383

# Misc. comments
I was trying to align the tooltip with the text. Instead of wasting more time on it I wanted to present some work and hopefully get some advice from you guys on how to accomplish it with out wasting so much time. 

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [ ] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] Ready to merge

### CODE REVIEW

**Comment by Germs31** [comment]
Screen Shot 2020-03-05 at 4 09 09 PM

Here is what i added. I think the styling is a little off I wanted to align it with the text but I felt I was wasting a little too much time so I moved on to the next one to come back to this. again, sorry for the late image.

**Comment by jimmykodes** [comment]
image

I made some changes to your icon, assuming I understand what you were trying to make work styling-wise. Here is what it looks like, and you can see in the code files what I did to make it look like that. Lemme know if you have any questions on this.

**Comment by Germs31** [comment]
oooooh right on! is that a component that you created? or is the sup tag something i never heard of? lol thats exactly what I was going for.

**Comment by jimmykodes** [comment]
`<sup>` and `<sub>` are html tags for superscript and subscript accordingly.

**Pull request merged**
