### PR TITLE
Competition bundle refactor + selenium tests for it

### PR DESCRIPTION
**Pull request by jimmykodes**
rebuilt competition unpacker with flat task yaml and wrote selenium tests for competition upload

Resolves issue #101

### CODE REVIEW

**Comment by jimmykodes** [comment]
Circle CI is real angry about the Selenium tests, not sure how to fix it?

**Comment by jimmykodes** [comment]
Just running collectstatic didn't fix the selenium issues. Other ideas? Not super sure where to even start debugging this.

**Comment by ckcollab** [comment]
Can you paste a screenshot of what it's doing? Hmm...

**Comment by jimmykodes** [comment]
screen shot 2019-02-26 at 5 33 37 pm
screen shot 2019-02-26 at 5 33 56 pm

**Comment by jimmykodes** [comment]
Still static file issues?

**Comment by ckcollab** [comment]
Could be:
 * Static files, still? or just a couple mixed up, like RIOT not being generated?
 * Collectstatic actually wasn't being ran still
 * Permissions of some kind ??

**Pull request merged**
